export var mensWear = [
  {
    type: "m",
  },
  {
    itemType: "formal-shirt",
    itemId: "0005M",
    itemTitle: "Blue Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172512000_iO.jpg"],
  },
  {
    itemType: "t-shirt",
    itemId: "0006M",
    itemTitle: "White T-Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_17251000_iOS.jpg"],
  },
  {
    itemType: "t-shirt",
    itemId: "0007M",
    itemTitle: "White T-Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/whiteshirt1.jpg",
      "./img/item-images/men/whiteshirt2.jpg",
    ],
  },
  {
    itemType: "formal-shirt",
    itemId: "0001M",
    itemTitle: "Yellow Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172512000_iOS.jpg"],
  },
  {
    itemType: "formal-pant",
    itemId: "0003M",
    itemTitle: "Red Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/redpant.jpg",
      "./img/item-images/men/redpant2.jpg",
      "./img/item-images/men/redpant3.jpg",
      "./img/item-images/men/redpant4.jpg",
    ],
  },
  {
    itemType: "formal-pant",
    itemId: "0004M",
    itemTitle: "Gray Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/gray_pant1.jpg",
      "./img/item-images/men/graypant2.jpg",
      "./img/item-images/men/graypant-3.jpg",
      "./img/item-images/men/graypant-4.jpg",
    ],
  },
  {
    itemType: "formal-pant",
    itemId: "0007M",
    itemTitle: "White Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/whitepant-1.jpg",
      "./img/item-images/men/whitepant-2.jpg",
      "./img/item-images/men/whitepant3.jpg",
      "./img/item-images/men/whitepant-4.jpg",
    ],
  },
  {
    itemType: "t-shirt",
    itemId: "0007M",
    itemTitle: "Black Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172540000_iOS.jpg"],
  },
  {
    itemType: "t-shirt",
    itemId: "0006M",
    itemTitle: "White T-Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_17251000_iOS.jpg"],
  },
  {
    itemType: "t-shirt",
    itemId: "0007M",
    itemTitle: "White T-Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/whiteshirt1.jpg",
      "./img/item-images/men/whiteshirt2.jpg",
    ],
  },
  {
    itemType: "formal-shirt",
    itemId: "0001M",
    itemTitle: "Yellow Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172512000_iOS.jpg"],
  },
  {
    itemType: "formal-pant",
    itemId: "0003M",
    itemTitle: "Red Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/redpant.jpg",
      "./img/item-images/men/redpant2.jpg",
      "./img/item-images/men/redpant3.jpg",
      "./img/item-images/men/redpant4.jpg",
    ],
  },
  {
    itemType: "formal-pant",
    itemId: "0004M",
    itemTitle: "Gray Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/gray_pant1.jpg",
      "./img/item-images/men/graypant2.jpg",
      "./img/item-images/men/graypant-3.jpg",
      "./img/item-images/men/graypant-4.jpg",
    ],
  },
  {
    itemType: "formal-pant",
    itemId: "0007M",
    itemTitle: "White Pant",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: [
      "./img/item-images/men/whitepant-1.jpg",
      "./img/item-images/men/whitepant-2.jpg",
      "./img/item-images/men/whitepant3.jpg",
      "./img/item-images/men/whitepant-4.jpg",
    ],
  },
  {
    itemType: "t-shirt",
    itemId: "0007M",
    itemTitle: "Black Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172540000_iOS.jpg"],
  },
  {
    itemType: "t-shirt",
    itemId: "0007M",
    itemTitle: "Black Shirt",
    itemPrice: 300,
    itemDescription: "This is a sample description",
    itemSize: "S M L XL XXL XXL",
    itemImages: ["./img/item-images/men/20200729_172540000_iOS.jpg"],
  },
];
