export var womensWear = [
  {
    type: "w",
  },
  {
    itemType: "category1",
    itemId: "0001W",
    itemTitle: "Women's Wear",
    itemPrice: 4000,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/reddress.jpg"],
  },
  {
    itemType: "category2",
    itemId: "0002W",
    itemTitle: "Women's Duppats",
    itemPrice: 40,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: [
      "./img/item-images/women/duppata_1.jpg",
      "./img/item-images/women/duppata_2.jpg",
      "./img/item-images/women/duppata_3.jpg",
      "./img/item-images/women/duppata_4.jpg",
      "./img/item-images/women/duppata_5.jpg",
    ],
  },
  {
    itemType: "category3",
    itemId: "0003W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172513000_iOS.jpg"],
  },
  {
    itemType: "category1",
    itemId: "0004W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/skybluedress.jpg"],
  },
  {
    itemType: "category2",
    itemId: "0005W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172813000_iOS.jpg"],
  },
  {
    itemType: "category3",
    itemId: "0004W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172515000_iOS.jpg"],
  },
  {
    itemType: "category1",
    itemId: "0006W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172516000_iOS.jpg"],
  },
  {
    itemType: "category2",
    itemId: "0004W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172715000_iOS.jpg"],
  },
  {
    itemType: "category3",
    itemId: "0009W",
    itemTitle: "Women's Dress",
    itemPrice: 400,
    itemDescription: "this is a sample Description",
    itemSize: "S M L XL XXL",
    itemImages: ["./img/item-images/women/20200729_172528000_iOS1.jpg"],
  },
];
